---
- name: Install ruby and rubygems and required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
