---
- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: Restart puma

    - name: Bundle install
      community.general.bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
    - name: Restart puma
      ansible.builtin.systemd:
        name: puma
        state: restarted
